# Prompt
prompt: Landscape, environment, scenery
uncondition_prompt: ""
cfg_scale: 4 # min: 1, max: 14

# input and output path, the file names should be
# [image_name].png or .jpg and [mask_name]_mask.png or .jpg
# Note the [image_name] and [mask_name] should be same
input_path: ./inputs/
output_path: ./temp/

# Path config
vocab_path: ./../data/vocab.json
merge_path: ./../data/merges.txt
checkpoint: ./../data/v1-5-pruned-emaonly.ckpt

# other config
seed: 42
sampler: ddpm
num_inference_steps: 50
device: cuda
mean_masking_stop: 0 #100
masking_stop: 0 # 50
stop_resampling: 500
jump_length: 5
cycle: 5