name: aipainter
channels:
  - defaults
dependencies:
  - python=3.11
  - lightning
  - numpy
  - pillow
  - pytorch
  - tqdm
  - transformers
  - torchvision
  - matplotlib
  - fastai::opencv-python-headless
  - opencv
  - anaconda::scipy
  - anaconda::scikit-learn
  - conda-forge::lpips
